src/lib/variants/screen.ts
src/utils/helpers.ts
test/processor/variant.test.ts

This pull request adds support for [custom media queries](https://tailwindcss.com/docs/breakpoints#custom-media-queries), [max-width breakpoints](https://tailwindcss.com/docs/breakpoints#max-width-breakpoints), and [multi-range breakpoints](https://tailwindcss.com/docs/breakpoints#multi-range-breakpoints) in the [`screens` configuration option](https://tailwindcss.com/docs/breakpoints).
This way, users that are using these types of breakpoints in `tailwindcss` can easily migrate to `windicss` without changing their configuration or setup.
Added tests that illustrate how the feature works.
Closes #15.

Add support for raw and min/max in custom screen definitions

---

src/utils/algorithm/sortSelector.ts

When sorting selectors, should make general utilities first.
Currently, utilities with the same leading letter will keep the input order, for example
`mt-8 m-4` will generate as
```css
.mt-8 {
/* ... */
}
.m-4 {
/* ... */
}
```
Which causes the `mt-8` been overridden by `m-4`.
This PR makes the sorting for StyleSheets aware of this and always generates `m-4` before `mt-8`. This matches the behavior of TailwindCSS.

fix(stylesheet): sort general utilities first

---

test/plugin/typography.test.ts

This PR adds a FAILED tests:
When using `theme: extend` with the typography plugin, it will generate incorrect CSS.
Config (it works fine if you don't extend it).
```js
theme: {
extend: {
typography: {
DEFAULT: {
css: {
color: 'red'
}
}
}
}
}
```
You can see the generated `typography.css`:
```css
.prose {
color: red;
}
.prose 0 {
color: #374151;
max-width: 65ch;
}
.prose 0 [class~="lead"] {
color: #4b5563;
}
.prose 0 a {
color: #111827;
text-decoration: underline;
font-weight: 500;
}
.prose 0 strong {
color: #111827;
font-weight: 600;
}
.prose 0 ol[type="A"] {
--list-counter-style: upper-alpha;
}
/* ... */
```

Failed test - typography extend bug

---

src/lib/index.ts
test/plugin/__snapshots__/aspectRatio.test.ts.yml
test/plugin/__snapshots__/lineClamp.test.ts.yml
test/plugin/aspectRatio.test.ts
test/plugin/lineClamp.test.ts
test/processor/__snapshots__/config.test.ts.yml
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/config.test.ts

Hi,
this tries to fix #105 
this also fixes some screen prefixes eg for .sm:animate-spin or .lg:btn
~~this still has a problem with the :hover in the "shortcuts config object" test
Does anybody have an idea how to fix?~~

fix: custom prefixes and screen prefixes

---

src/lib/utilities/dynamic.ts

While not documented, tailwindcss' container component has support for specific screens configuration.
https://github.com/tailwindlabs/tailwindcss/blob/38b4eeb288ec5e43c28c6ffbc7f3353120c475fd/src/plugins/container.js#L71
This adds the same behaviour to windicss.

Adds support for container.screens config

---

src/lib/utilities/dynamic.ts

Hi,
i added grid-gap, grid-column-gap, grid-row-gap for older browsers if prefixer is enabled
for example Safari before 12.1 still used the old syntax:
https://caniuse.com/mdn-css_properties_column-gap_grid_context

fix: add grid-(column-|row-)gap for older browsers

---

src/utils/parser/css.ts
test/parser/css.test.ts

fixes #139
another option would be:
const content = this.parse(css.slice(index, nestEnd) + ';', selector);
or maybe theres a better approach?

fix: allow last rule in block without semicolon

---

src/lib/utilities/dynamic.ts
src/utils/tools.ts
test/processor/config.test.ts
test/utils/tools.test.ts

See: https://github.com/windicss/nuxt-windicss-module/issues/21
If the user is using an existing tailwind config then some of the options are undefined, specifically, these lines of code are throwing the issue.
```
const positions = toType(theme('backgroundPosition'), 'object') as { [key: string]: string };
// positions is undefined
if (Object.keys(positions).includes(body)) 
```
I'm aware this is creating some inconsistent behaviours with how the object to type works versus the others, but I feel like if a function is called toType, it should honour that and return the type specified, regardless of the value provided. Can update the others as well if you'd like but wanted to keep the scope smaller.
With this, we don't need to rely on using a null coalescing whenever we are accessing the …

fix: always return an object type

---

src/lib/utilities/dynamic.ts

For example when you have both `.placeholder-emerald-400` and `.placeholder-opacity-40`, the style below will be used.
```css
.placeholder-opacity-40 {
--tw-placeholder-opacity: 0.4;
}
.placeholder-emerald-400::placeholder {
--tw-placeholder-opacity: 1;
color: rgba(52, 211, 153, var(--tw-placeholder-opacity));
}
```
Because `--tw-placeholder-opacity` is overridden by `.placeholder-emerald-400`'s one, `.placeholder-opacity-40` will not be applied.
This PR changes `.placeholder-opacity-40`'s style to below.
```css
.placeholder-opacity-40::placeholder {
--tw-placeholder-opacity: 0.4;
}
```

fix: apply placeholder-opacity with placeholder-color

---

src/helpers/config.ts
src/interfaces.ts

This PR only introduces changes to types, the implementation should be done on the tooling side.
A new type `FullConfig` is introduced for type `windi.config.ts` with extra options that consumed by tools but not the processor.

feat(types): update types to have centerized options for tools

---

src/plugin/filters/index.ts
test/interface/__snapshots__/config.test.ts.yml
test/plugin/filters.test.ts

Fixing the current `blur` filter to use the `blur()` method, see https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur()

fix(plugin): fix blur filter

---

src/lib/utilities/dynamic.ts
test/processor/plugin.test.ts

This enables working with CSS vars that are placed inside of other CSS functions, like rgba and hsla.  Instead of going through the `toColor` utility, the values are returned as-is.
This enables DaisyUI’s color theming to work beautifully.  I’m also amazed at how much simpler the API is compared to the TailwindCSS syntax.  Nice job, guys!
DaisyUI includes a set of [color utilities](https://daisyui.netlify.app/core/colors) for Tailwind that use `hsla()` colors with nested variables inside the parentheses.  Each color util has this format:
```js
{
primary: `hsla(var(--p, 259, 94%, 51%) / var(--tw-bg-opacity, 1))`
}
```
I noticed that `dynamic.ts` already include branching logic for property values that begin with `"var"`.  I've updated each line to check for `"var"` anywhere inside the …

feat: handle CSS vars anywhere in a property value

---

src/lib/utilities/handler.ts
src/utils/tools.ts
test/interface/__snapshots__/config.test.ts.yml
test/processor/__snapshots__/interpret.test.ts.yml
test/processor/interpret.test.ts
test/utils/tools.test.ts

As discussed in https://github.com/windicss/windicss/discussions/181#discussioncomment-514698
This PR enabled Tailwind JIT compatible "square brackets" syntax (credit to tailwind jit). It makes a thing like `p-[2em]` just works as `p-2em`.
While this PR only introduces the support for "square brackets", but not the configure to disabled the implicitly one. Which should be fairly easy to implement, but I am not sure how to name the field nor make it flexible enough for future needs. Proposals here
Proposal A
```ts
// windicss
export default {
autoInfer: 'explict-only' | false | true
}
```
Proposal B
```ts
// windicss
export default {
autoInfer: {
strict: true,
units: ['em', 'px'] // only enabled a few units
}
}
```
Proposal C
```ts
// windicss
export default {
strictAutoInfer: true
}
``` …

feat: support interpret square brackets

---

src/lib/utilities/dynamic.ts
test/processor/__snapshots__/interpret.test.ts.yml
test/processor/interpret.test.ts

For example when you have `.space-y-4` and `.space-y-reverse`, the style below will be used.
```css
.space-y-4 > :not([hidden]) ~ :not([hidden]) {
--tw-space-y-reverse: 0;
margin-top: calc(1rem * calc(1 - var(--tw-space-y-reverse)));
margin-bottom: calc(1rem * var(--tw-space-y-reverse));
}
.space-y-reverse {
--tw-space-y-reverse: 1;
}
```
`--tw-space-y-reverse: 1` will not be applied.
This PR changes `.space-y-reverse`'s style to below.
```css
.space-y-reverse > :not([hidden]) ~ :not([hidden]) {
--tw-space-y-reverse: 1;
}
```
This will fix `.space-x-reverse` and `.space-y-reverse` which are not working for now.

fix: apply --tw-space-*-reverse to child

---

src/helpers/transform.ts

When importing transform helper (`windicss/helpers`) in an ESM enviroment, require is undefined, according [node docs](https://nodejs.org/api/esm.html#esm_no_require_exports_or_module_exports) one should use createRequire to create the function. Interop with commonjs is done by typescript transformations, so it's also working there.

Fix undefined require on ESM env

---

src/lib/utilities/handler.ts

When use example config
```ts
// windi.config.ts
import { defineConfig } from 'windicss/helpers'
export default defineConfig({
/* configurations... */
})
```
build to javascript throw error
```bash
node_modules/windicss/types/lib/utilities/handler.d.ts:2:49 - error TS2307: Cannot find module 'src/interfaces' or its corresponding type declarations.
2 import type { colorCallback, colorObject } from 'src/interfaces';
```

fix: import relative path in lib/utilites/handler.ts

---

.github/workflows/test.yml

Nodejs v15 is EOL on June 1st.
https://github.com/nodejs/Release#release-schedule

chore: drop node v15

---

src/utils/tools.ts
test/utils/tools.test.ts

fixes #364
and also fixes some escaping issues like
```css
.some-class:after {
content: '\\';
}
```
or
```css
.some-class {
content: "'";
}
```

fix: data uris without quotes and escaping

---

src/utils/parser/class.ts

Sometimes there are has parenthesis in expressions when we use template syntax.
For example:
```html
<div class="text-black bg-white {{ ( conditionA || conditionB ) ? 'flex' : 'block' }}"></div>
```
When we use CLI interpretation mode.
Classname parse will end early.

fix: update condition for end group in ClassParser

---

src/config/colors.ts

Simply added sky color which actually is `lightBlue` renamed. `lightBlue` values have been left intact as is.

fix: add sky color

---

src/lib/utilities/dynamic.ts
test/processor/__snapshots__/utilities.test.ts.yml

This pull request fixes a typo in the `animateIterationCount` utility that causes the generated CSS to be incompatible with non-Webkit browsers.
```css
.animate {
-webkit-animation-iteration-count: 1;
aniamtion-iteration-count: 1
}
```
```css
.animate {
-webkit-animation-iteration-count: 1;
animation-iteration-count: 1
}
```

fix: Typo in animation-iteration-count breaks animation repeat utilities

---

src/lib/utilities/dynamic.ts
test/assets/windi.plugin.config.js
test/processor/__snapshots__/config.test.ts.yml
test/processor/config.test.ts

This pull request fixes a bug in the [`container`](https://windicss.org/utilities/container.html#container) utility which was causing custom breakpoints to be rendered incorrectly.
For example, when using a custom breakpoint such as `min/max` or `raw`:
```
import { defineConfig } from 'vite-plugin-windicss'
export default defineConfig({
theme: {
extend: {
screens: {
print: { raw: 'print' },
},
},
})  
```
it would generate invalid CSS:
```css
@media (min-width: [object Object]) {
.container {
max-width:[object Object]
}
}
```
Supporting `min/max` or `raw` entrypoints would not make sense for the [`container`](https://windicss.org/utilities/container.html#container) utility, as it's purpose is to simplify layout when using a mobile-first approach.

fix: Container utilities should only output standard min-width rules

---

src/cli/index.ts
src/cli/utils.ts
src/config/colors.ts
src/utils/tools.ts

Console is now used in https://github.com/windicss/windicss/blob/d827f96ab1eb6609bd6500c9a735d722d0588063/src/config/colors.ts#L1
therefore, when building, the complete cli/utils.ts gets included
and you cant use windicss in the browser anymore, because of the imports (fs, path, glob, minimatch)
so moving Console to utils/tools to fix this

fix: move Console to utils/tools, so cli/utils isnt build into main entry

---

src/lib/utilities/dynamic.ts
test/processor/utilities.test.ts

https://github.com/windicss/vite-plugin-windicss/pull/252
`content-` should not output, use `content-DEFAULT` instead.

fix: skip empty content utility

---

src/config/base.ts
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/utilities.test.ts

https://github.com/windicss/vite-plugin-windicss/pull/252
tailwind will auto add `content: ""` to *pseudo*:contents:
```css
/* contents */
.contents {
display: contents;
}
/* after:contents */
.after\:contents::after {
content: "";
display: contents;
}
```
I'm not sure it's fit to resolve this by adding a plugin in the default config.

fix: add default content to pseudo element with `contents`

---

src/plugin/scroll-snap/index.ts
test/plugin/scrollSnap.test.ts

This adds the `.snap-align-none` utility class as Windi CSS does not yet support it.
```css
.snap-align-none {
scroll-snap-align: none;
}
```
- Windi CSS docs: https://windicss.org/plugins/official/scroll-snap.html
- Tailwind v3 docs https://tailwindcss.com/docs/scroll-snap-align

Add 'scroll-snap-align: none' utility class

---

src/config/order.ts
src/lib/utilities/static.ts
src/utils/completions.ts
test/processor/__snapshots__/resolve.test.ts.yml
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/resolve.test.ts
test/processor/utilities.test.ts
test/utils/__snapshots__/completions.test.ts.yml

This adds the `.touch-x` and `.scroll-x` classes.
- https://tailwindcss.com/docs/touch-action
- https://tailwindcss.com/docs/scroll-behavior

feat: add '.touch-x' and '.scroll-x' utility classes

---

src/config/base.ts
src/config/order.ts
src/interfaces.ts
src/lib/index.ts
src/lib/variants/index.ts
src/lib/variants/orientation.ts
test/processor/__snapshots__/variant.test.ts.yml
test/processor/resolve.test.ts
test/processor/variant.test.ts

This adds the `portrait:` and `landscape:` variants.
- https://tailwindcss.com/docs/hover-focus-and-other-states#viewport-orientation

feat: add 'portrait:' and 'landscape:' variants

---

src/config/base.ts
src/lib/utilities/dynamic.ts
src/lib/utilities/static.ts
src/utils/completions.ts
test/processor/__snapshots__/attributify.test.ts.yml
test/processor/__snapshots__/config.test.ts.yml
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/resolve.test.ts
test/processor/utilities.test.ts
test/utils/__snapshots__/completions.test.ts.yml

This adds the ability to use classes like `.shadow-red-800/50`
@antfu This should be the last PR to bring Windi up-to-date with Tailwind v3 (for now)

feat: add ability to use opacity values for box-shadows

---

src/config/order.ts
src/lib/utilities/dynamic.ts
test/processor/__snapshots__/resolve.test.ts.yml
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/utilities.test.ts

This PR adds the `.accent-x` utility class which allows the user to control the `accent-color` CSS property.
- https://tailwindcss.com/docs/accent-color
- https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

feat: add '.accent-x' utility class

---

src/config/order.ts
src/lib/variants/state.ts
test/processor/__snapshots__/variant.test.ts.yml
test/processor/resolve.test.ts

This PR adds the `file:` variant. Windi already provides this functionality via the `file-selector-button:` variant. I kept this variant to be backwards compatible.
- https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons

feat: add 'file:' variant

---

src/lib/index.ts
test/processor/__snapshots__/attributify.test.ts.yml
test/processor/attributify.test.ts

As a common CSS property, gap has already been defined in utilities/dynamic.ts.
In this feature, some unnecessary css code will be generated by `dynamicUtilities.gap`, but this does not affect the user's application.
See also: [Supported in Flex Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/gap#browser_compatibility)

feat: support gap property in flex attribute (#582)

---

src/utils/parser/class.ts
test/parser/__snapshots__/class.test.ts.yml
test/parser/class.test.ts

```typescript
it('parse function with parameter deconstruction', () => {
const badClasses = 'function ComponentA({ name }: Props) { return div className= grid }';
const goodClasses = '{ return div className= grid }';
const badResult = new ClassParser(badClasses, ':', []).parse();
const goodResult = new ClassParser(goodClasses, ':', []).parse();
const findGrid = (els: any[]) => els.find(item => item.raw === 'grid');
expect(findGrid(badResult)).toBeTruthy();
expect(findGrid(goodResult)).toBeTruthy();
});
```
Both of `badClasses` and `goodClasses` should return a `element.raw === 'grid'`.
```typescript
it('parse function with parameter deconstruction', () => {
const classes = 'function ComponentA({ name } Props) { return div className= grid }';
const result = new ClassParser(classes, ':', …
```

fix: ClassParser incorrectly end group with jsx functional component content

---

src/lib/index.ts
src/lib/preflight.ts

This fixes issue #514 and enables the possibility of a preflight safelist, as documented https://windicss.org/guide/extractions.html#preflight.

fix(cli): Preflight not working with CLI, close #514

---

src/jsx.ts

fix(jsx): add missing attribute declaration in jsx

---

src/cli/index.ts

Previously, I had submitted this PR: https://github.com/windicss/vite-plugin-windicss/pull/257 which enabled me to use syntax like `h = 20`. I tried doing the same with `<style>` block. My code was like:
```HTML
<style
lang = "windi">
/* some stuff */
</style>
```
This never did anything until I changed my style block to:
```html
<style lang="windi">
/* some stuff */
</style>
```
Because of the `attributify` mode, I'm trying to use all attributes of all tags in a new line to maintain consistency. Thus, when I did the way I did before, it was not working.
This PR changes the style block matching regex to match the above mentioned syntax. Please consider merging it.

fix(cli): whitespace and line-break support to style block

---

src/lib/preflight.ts

This should fix #666. The solution is create an additional `StyleSheet` for plugin, separate `sort` for each `StyleSheet` then `extend`.

fix: StyleSheet sort makes plugin doesn't work as expected (#666)

---

src/utils/color.ts

hsl2rgb performance increased by ~10%
toRGB performance increased by ~50%
performance measurements were gathered using my own tests with random colors

perf: optimize utils/color.ts

---

src/config/colors.ts
src/utils/color.ts

changes:
- added a function for color renamed warnings
- renamed `zink` to `zinc`
- renamed `warmGray` to `stone`
- renamed `blueGray` to `slate`
- renamed `trueGray` to `neutral`
- renamed `coolGray` to `gray`
* `gray` should have always had the same colors as `coolGray` but for some reason didn't.

feat: improve TW3 color support

---

src/config/base.ts

follow-up : #710
#710 will use the default color before renaming, so you will get a warning without doing anything.

fix: fix default colors to set renamed colors

---

README.md

Now badge shows correct version number.
Before
After

docs: Fixed old npm link
