src/cli/utils.ts

fix(typo): creatation -> creation

---

.github/workflows/publish.yml
.github/workflows/test.yml
CONTRIBUTING.md
package-lock.json
package.json
rollup.config.js

Every time you would like to drop a new release, `npm run release` and select the version then you are good to go. Build and publishing are finished on the CI.

chore: setup CI release

---

.gitignore
package-lock.json
package.json
test/extend.d.ts
test/processor/__snapshots__/compile.test.ts.yml
test/processor/__snapshots__/config.test.ts.yml
test/processor/__snapshots__/interpret.test.ts.yml
test/processor/compile.test.ts
test/processor/config.test.ts
test/processor/interpret.test.ts
test/run.ts
tsconfig.json

This PR intoduce snapshot for Jasmine.
Usage
```ts
expectToMatchSnapshot(styleSheet.build(), "css", __filename);
```
Snapshot files will be generated under `__snapshots__` folder.
Run `npm run test:update` to force the snapshots to update.

test: setup snapshot tests

---

src/lib/utilities/dynamic.ts

Closes #59 
Change container classes padding property to padding-left and padding-right.

Fix container class

---

src/plugin/typography/index.ts
src/utils/algorithm/combineConfig.ts
test/plugin/__snapshots__/typography.test.ts.yml
test/plugin/typography.test.ts

fix: plugin theme extending bug

---

src/plugin/typography/styles.ts
test/plugin/__snapshots__/typography.test.ts.yml

refactor(typography): ul, ol ::marker pseudo dublicates

---

src/utils/style/base.ts
src/utils/tools.ts
test/parser/__snapshots__/css.test.ts.yml
test/parser/css.test.ts
test/style/property.test.ts
test/utils/tools.test.ts

Related https://github.com/windicss/vite-plugin-windicss/issues/49

Failed test: css transform trunc data url

---

src/utils/parser/css.ts
test/parser/__snapshots__/css.test.ts.yml
test/parser/css.test.ts

Support nested CSS syntax similar to sass/less.
close #133, close #131, close #114

feat: new css parser, support nested css.

---

README.md

not the prettiest but get the stuff done with auto update, until people with better design skill than me can improve it :)

docs: add section to show love to our sponsors

---

src/utils/parser/css.ts
test/parser/__snapshots__/css.test.ts.yml
test/parser/css.test.ts

fix https://github.com/windicss/windicss/issues/190

fix: remove comment shouldn't remove url, close #190

---

src/utils/style/base.ts
test/style/__snapshots__/prefixer.test.ts.yml
test/style/prefixer.test.ts

fix: disable prefixer, close #132

---

src/utils/tools.ts
test/processor/__snapshots__/config.test.ts.yml
test/processor/config.test.ts

Dashify now 100% compatible with TailwindCSS/PostCSS

fix: dashify, close #218

---

src/lib/utilities/dynamic.ts
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/utilities.test.ts

fix: container padding option on root as default

---

src/config/index.ts
src/utils/algorithm/sortMediaQuery.ts
src/utils/tools.ts

The Wechat MiniProgram define a [rpx](https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxss.html#Dimension-Unit) unit.

feat: add `rpx` unit for value auto-infer

---

src/lib/utilities/static.ts

Fixes https://github.com/windicss/windicss/issues/343 grid-auto-flow : column dense, similar to https://tailwindcss.com/docs/grid-auto-flow

fix-issue-343

---

rollup.config.js

Simply fix plugins' types declaration file path

fix: plugins types declaration file path

---

src/lib/utilities/dynamic.ts
test/processor/__snapshots__/interpret.test.ts.yml
test/processor/interpret.test.ts

feat: handle fraction for padding and margin, close #415

---

.vscode/settings.json
CONTRIBUTING.md
playground/index.html
playground/package.json
playground/windi.config.js
pnpm-lock.yaml
pnpm-workspace.yaml

cc @alexanderniebuhr 
---
Commit messages:
```
docs(CONTRIBUTING.md): add instructions
Add instructions for testing on a real world
project.
feat: add testing project
build(settings.json): add settings for vscode live server
```

docs: add instructions for testing

---

src/utils/style/sheet.ts
test/parser/__snapshots__/css.test.ts.yml
test/parser/css.test.ts
test/processor/__snapshots__/attributify.test.ts.yml
test/processor/__snapshots__/compile.test.ts.yml
test/style/sheet.test.ts

Fix an edge case of layers with the same tag name, see also: https://github.com/windicss/vite-plugin-windicss/issues/260#issuecomment-986467399

fix(parser): fix wrong layer combination

---

src/config/order.ts
src/lib/utilities/static.ts
src/utils/completions.ts
test/processor/__snapshots__/resolve.test.ts.yml
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/resolve.test.ts
test/processor/utilities.test.ts
test/utils/__snapshots__/completions.test.ts.yml

This adds the `.will-change-x` classes.
- https://tailwindcss.com/docs/will-change

feat: add '.will-change-x' utility class

---

src/lib/utilities/handler.ts

This PR adds `inherit` to the color functions as PR #601 introduced this new color.

chore: add  'inherit' color to color functions

---

src/utils/tools.ts
test/utils/tools.test.ts

fix: Maximum call stack size exceeded at guessClassName

---

src/utils/tools.ts

I add several absolute length units: cm, mm, in, pt, pc.
It looks like Unocss already has them.

feat: add sizes in cm, mm, in, pt, pc

---

src/lib/utilities/dynamic.ts
test/processor/__snapshots__/utilities.test.ts.yml
test/processor/utilities.test.ts

feat: add border-x and border-y utility classes (#711)
